-- 1. List all books with their authors.
SELECT B.BOOKID, B.TITLE, A.AUTHORNAME
FROM BOOK B
LEFT JOIN AUTHOR A ON B.AUTHORID = A.AUTHORID;

-- 2. List all books with their publishers.
SELECT B.BOOKID, B.TITLE, P.PUBLISHERNAME
FROM BOOK B
LEFT JOIN PUBLISHER P ON B.PUBLISHERID = P.PUBLISHERID;

-- 3. List all books with their authors and publishers.
SELECT B.BOOKID, B.TITLE, A.AUTHORNAME, P.PUBLISHERNAME
FROM BOOK B
LEFT JOIN AUTHOR A ON B.AUTHORID = A.AUTHORID
LEFT JOIN PUBLISHER P ON B.PUBLISHERID = P.PUBLISHERID;

-- 4. List all books published after 2010 with their authors and publisher and price.
SELECT B.BOOKID, B.TITLE, A.AUTHORNAME, P.PUBLISHERNAME, B.PRICE, B.PUBLICATIONYEAR
FROM BOOK B
LEFT JOIN AUTHOR A ON B.AUTHORID = A.AUTHORID
LEFT JOIN PUBLISHER P ON B.PUBLISHERID = P.PUBLISHERID
WHERE B.PUBLICATIONYEAR > 2010
ORDER BY B.PUBLICATIONYEAR;

-- 5. List all authors and the number of books they have written.
SELECT A.AUTHORID, A.AUTHORNAME, COUNT(B.BOOKID) AS BookCount
FROM AUTHOR A
LEFT JOIN BOOK B ON A.AUTHORID = B.AUTHORID
GROUP BY A.AUTHORID, A.AUTHORNAME;

-- 6. List all publishers and the total price of books they have published.
SELECT P.PUBLISHERID, P.PUBLISHERNAME, SUM(B.PRICE) AS TotalPrice
FROM PUBLISHER P
LEFT JOIN BOOK B ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY P.PUBLISHERID, P.PUBLISHERNAME;

-- 7. List authors who have not written any books.
SELECT A.AUTHORID, A.AUTHORNAME
FROM AUTHOR A
LEFT JOIN BOOK B ON A.AUTHORID = B.AUTHORID
WHERE B.BOOKID IS NULL;

-- 8. Display the total number of books written by each author along with the average price of their books.
SELECT A.AUTHORNAME, COUNT(B.BOOKID) AS BookCount, AVG(B.PRICE) AS AvgPrice
FROM AUTHOR A
LEFT JOIN BOOK B ON A.AUTHORID = B.AUTHORID
GROUP BY A.AUTHORNAME;

-- 9. List each publisher along with the total number of books they have published, sorted from highest to lowest.
SELECT P.PUBLISHERNAME, COUNT(B.BOOKID) AS BookCount
FROM PUBLISHER P
LEFT JOIN BOOK B ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY P.PUBLISHERNAME
ORDER BY BookCount DESC;

-- 10. Display number of books published each year.
SELECT B.PUBLICATIONYEAR, COUNT(*) AS BooksPublished
FROM BOOK B
GROUP BY B.PUBLICATIONYEAR
ORDER BY B.PUBLICATIONYEAR;